### ISSUE TITLE
HRToVRC breaks my gestures and some animations

### ISSUE THREAD

**Issue by Lupsoris** [200Tigersbloxed/HRtoVRChat_OSC#7] opened 2022-05-11 23:03 UTC
Hello !

I wanted to add HRtoVRC to my avatar, except that it completely breaks my gestures and animations.

For example, the animations aren't fully reset to the Idle animation (you can also notice that the tongue is still active because the animation is surely a bit activated), my tail that's supposed to move doesn't move anymore, the animations of the ears linked to the gestures don't work, etc.

Here's a video that shows the import, the addition to the avatar (totally basic), the upload and the before/after test: https://streamable.com/sa3izx

I hope that a solution can be found,
Thank you,
Lupsoris

**Comment by 200Tigersbloxed** [comment] 2022-05-11 23:07
Hi, this is a very common issue with Write Defaults. When you were Creating the Animations, I noticed you had Write Defaults disabled. While VRChat recommends this, most of the time, people make animations with Write Defaults On. So, when you mix the two, it tends to cause issues like this, most notably, gestures getting stuck.

The solution here is to Create the Animations again, however this time, be sure to enable Write Defaults in the options tab, then get back to me if that worked or not 😸

**Comment by Lupsoris** [comment] 2022-05-12 21:28
Hello,

It works, so I'm sorry I created an "Issues" for nothing.

Maybe think about adding the information, or the advice to check this if people have a gesture/animation problem.

Thanks,
Lupsoris

**Comment by 200Tigersbloxed** [comment] 2022-05-12 21:34
Yeah, I'm planning on adding it to the FAQ section of the wiki for future references, as I've had a couple of peeps inquire this on the discord server already. However, this issue will be a great reference example for those who think they have the same issue or not, as the issue is very informative! Thanks much!

(closing unless needed)

**Closed by 200Tigersbloxed** 2022-05-12 21:34 UTC
Labels: good first issue
